import pyautogui
import keyboard
import time
import pydirectinput
import keyboard

if __name__ == "__main__":
    print("뽑기 시작")
    pydirectinput.click(1515, 1030, button = 'left')
    pydirectinput.mouseDown() 
    pydirectinput.mouseUp()
    time.sleep(0.5)
    pydirectinput.click(1095, 690, button = 'left')
    pydirectinput.mouseDown() 
    pydirectinput.mouseUp()
    time.sleep(0.5)
    i = 0
    for i in range(10):
        pydirectinput.click(1515, 1030, button = 'left')
        pydirectinput.mouseDown() 
        pydirectinput.mouseUp()
        time.sleep(2)
    pydirectinput.click(1575, 250, button = 'left')
    pydirectinput.mouseDown() 
    pydirectinput.mouseUp()
    time.sleep(0.5)
    pydirectinput.click(1515, 1030, button = 'left')
    pydirectinput.mouseDown() 
    pydirectinput.mouseUp()
    time.sleep(0.5)
    pydirectinput.click(1095, 690, button = 'left')
    pydirectinput.mouseDown() 
    pydirectinput.mouseUp()
    time.sleep(0.5)
    i = 0
    for i in range(10):
        pydirectinput.click(1515, 1030, button = 'left')
        pydirectinput.mouseDown() 
        pydirectinput.mouseUp()
        time.sleep(2)
    pydirectinput.click(1690, 250, button = 'left')
    pydirectinput.mouseDown() 
    pydirectinput.mouseUp()
    time.sleep(0.5)
    pydirectinput.click(1515, 1030, button = 'left')
    pydirectinput.mouseDown() 
    pydirectinput.mouseUp()
    time.sleep(0.5)
    pydirectinput.click(1095, 690, button = 'left')
    pydirectinput.mouseDown() 
    pydirectinput.mouseUp()
    time.sleep(0.5)
    i = 0
    for i in range(10):
        pydirectinput.click(1515, 1030, button = 'left')
        pydirectinput.mouseDown() 
        pydirectinput.mouseUp()
        time.sleep(2)
    pydirectinput.click(1785, 250, button = 'left')
    pydirectinput.mouseDown() 
    pydirectinput.mouseUp()
    time.sleep(0.5)
    pydirectinput.click(1515, 1030, button = 'left')
    pydirectinput.mouseDown() 
    pydirectinput.mouseUp()
    time.sleep(0.5)
    pydirectinput.click(1095, 690, button = 'left')
    pydirectinput.mouseDown() 
    pydirectinput.mouseUp()
    time.sleep(0.5)
    pydirectinput.click(1515, 1030, button = 'left')
    pydirectinput.mouseDown() 
    pydirectinput.mouseUp()
    time.sleep(1)
    pydirectinput.click(1735, 1030, button = 'left')
    pydirectinput.mouseDown() 
    pydirectinput.mouseUp()
    time.sleep(1)
    pydirectinput.click(1305, 370, button = 'left')
    pydirectinput.mouseDown() 
    pydirectinput.mouseUp()
    time.sleep(1)
    pydirectinput.click(1115, 495, button = 'left')
    pydirectinput.mouseDown() 
    pydirectinput.mouseUp()
    time.sleep(1)
    pydirectinput.click(1115, 780, button = 'left')
    pydirectinput.mouseDown() 
    pydirectinput.mouseUp()
    time.sleep(1)
